package com.fintrack.constants;

public enum KafkaTopics {
    MARKET_DATA_UPDATE_REQUEST("MARKET_DATA_UPDATE_REQUEST"),
    MARKET_DATA_UPDATE_COMPLETE("MARKET_DATA_UPDATE_COMPLETE"),
    MARKET_INDEX_DATA_UPDATE_REQUEST("MARKET_INDEX_DATA_UPDATE_REQUEST"),
    MARKET_INDEX_DATA_UPDATE_COMPLETE("MARKET_INDEX_DATA_UPDATE_COMPLETE"),
    HISTORICAL_MARKET_DATA_REQUEST("HISTORICAL_MARKET_DATA_REQUEST"),
    HISTORICAL_MARKET_DATA_COMPLETE("HISTORICAL_MARKET_DATA_COMPLETE");

    private final String topicName;

    KafkaTopics(String topicName) {
        this.topicName = topicName;
    }

    public String getTopicName() {
        return topicName;
    }
}