package com.fintrack.constants;

public enum KafkaTopics {
    TRANSACTIONS_CONFIRMED("TRANSACTIONS_CONFIRMED"),
    PROCESS_TRANSACTIONS_TO_HOLDINGS_COMPLETE("PROCESS_TRANSACTIONS_TO_HOLDINGS_COMPLETE"),
    MARKET_DATA_UPDATE_REQUEST("MARKET_DATA_UPDATE_REQUEST"),
    MARKET_DATA_UPDATE_COMPLETE("MARKET_DATA_UPDATE_COMPLETE"),
    MARKET_AVERAGE_DATA_UPDATE_REQUEST("MARKET_AVERAGE_DATA_UPDATE_REQUEST"),
    MARKET_AVERAGE_DATA_UPDATE_COMPLETE("MARKET_AVERAGE_DATA_UPDATE_COMPLETE"),
    HISTORICAL_MARKET_DATA_REQUEST("HISTORICAL_MARKET_DATA_REQUEST"),
    HISTORICAL_MARKET_DATA_COMPLETE("HISTORICAL_MARKET_DATA_COMPLETE"),
    FOREX_DATA_UPDATE_REQUEST("FOREX_DATA_UPDATE_REQUEST"),
    FOREX_DATA_UPDATE_COMPLETE("FOREX_DATA_UPDATE_COMPLETE");

    private final String topicName;

    KafkaTopics(String topicName) {
        this.topicName = topicName;
    }

    public String getTopicName() {
        return topicName;
    }
}