version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - APP_BASE_URL=${APP_BASE_URL}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      # MailHog for dev/local
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - MAIL_SMTP_AUTH=false
      - MAIL_SMTP_STARTTLS_ENABLE=false
      - STRIPE_SECRET_KEY=${STRIPE_TEST_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_TEST_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_TEST_WEBHOOK_SECRET}
    depends_on:
      - kafka
      - db
      # Only include mailhog in dev/local, not prod
    networks:
      - ${DATABASE_NETWORK_NAME}

  kafka:
    image: confluentinc/cp-kafka:7.4.0 # Use Confluent Kafka image with CLI tools
    ports:
      - "9092:9092" # Host communication
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - ${DATABASE_NETWORK_NAME}

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ${DATABASE_NETWORK_NAME}

  etl:
    build:
      context: ../financial-tracker-etl
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9093 # Use the DOCKER listener for inter-container communication
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ${DATABASE_NETWORK_NAME}

networks:
  ${DATABASE_NETWORK_NAME}:
    external: true